namespace: default

image:
  repository: us.gcr.io/octane-public/octane-collector
  tag: 0.0.2

ledgerHost: "http://octane-ledger:8080"

queue:
  storageClassName: standard
  sizeGB: 10
  pushIntervalMinutes: 1

surveyingIntervalMinutes: 1
meteringIntervalMinutes: 1

enableK8SMetricsSurveyor: "true"

opaGatekeeperEnabled: false
